version: '3.2'

services:

  tests:
    image: nekroze/containaruba:latest
    command:
      - --order=random
    volumes:
      - ./subcommander:/usr/bin/subcommander:ro
      - ./features:/usr/src/app/features
